package com.ja3son.libdemo.Sample7_7;

public enum BodyPartIndex {
	
	BODYPART_HEAD,//ͷ
	BODYPART_SPINE,//����
	BODYPART_PELVIS,//����

	BODYPART_LEFT_UPPER_ARM,//����
	BODYPART_RIGHT_UPPER_ARM,//�Ҵ��
	
	BODYPART_LEFT_LOWER_ARM,//��С��
	BODYPART_RIGHT_LOWER_ARM,//��С��

	BODYPART_LEFT_UPPER_LEG,//�����
	BODYPART_RIGHT_UPPER_LEG,//�Ҵ���
	
	BODYPART_LEFT_LOWER_LEG,//��С��
	BODYPART_RIGHT_LOWER_LEG,//��С��

	BODYPART_COUNT;
}
